### ISSUE TITLE
GDStoSVG.exe -help not working

### ISSUE THREAD

**Issue by ronaldomponte** [CaiB/GDStoSVG#1]
The command GDStoSVG.exe -help is not working.
The output is:
-------------------------------------------
CSV file not specified or not found.
Could not find GDS file "-help".
-------------------------------------------
Can you provide what is the required format for the CSV file?
Thank you.

**Comment by CaiB** [comment]
Oops, sorry, that was a rather silly thing to overlook on my part. I just pushed an update that should fix this issue.
The CSV file should have no header, and each line should contain:
`<Name>,<ID in range -32768 to 32767>,<Colour as RRGGBB hex>,<Opacity in range 0.0 to 1.0>`
Layers will be stacked in list order, with the bottom line of CSV file on top in SVG.
For example:
`M3,300,FF0000,0.8`
The values above are a fictional example, and the actual numbers you need will depend on your PDK. You can get the layer mapping info from another tool in your flow. Once you have that, just follow the instructions on the main README to finish setting up.

I've found that if your design is reasonably large, Inkscape will simply not be able to handle the resulting SVG file. I was looking into merging polygons in GDStoSVG before export to try to alleviate this somewhat, but never got around to it. Let me know if your design is too large to open once exported and I'll come back around and give it a go. Inkscape's polygon union is also insanely slow.
